import CPLMonitor.LocalEval

/-!
Receive-merge core for the monitor update.

The full event-update proof will instantiate this file with the
latest-visible events before the receive and the latest-visible events
carried by the incoming message.  This file proves the algorithmic core:
componentwise maximum of vector-clock entries selects the corresponding
latest-value views.
-/

namespace CPLMonitor

variable {L Event Var Val Pred : Type}

/-- Latest visible event selection for one lifeline when merging two
causal snapshots.  `none` has clock value `0`; real events have positive
indices by `MSC.localIndex_pos`. -/
def chooseLatest (M : MSC L Event Var Val) :
    Option Event → Option Event → Option Event
  | none, none => none
  | some e, none => some e
  | none, some f => some f
  | some e, some f =>
      if M.localIndex e < M.localIndex f then some f else some e

/-- Latest-visible map of a lifeline immediately before its current
local event, represented by the previous local event if it exists. -/
def latestBeforeLocal (M : MSC L Event Var Val) (e : Event) (B : L) :
    Option Event :=
  match M.prevLocal e with
  | none => none
  | some p => M.latestVisible p B

/-- Causal shape of a receive event.  This does not impose FIFO.  It only
states that the causal predecessors of the receive are generated by the
previous local event and the matching send, plus the receive event itself. -/
structure ReceiveCausalContext (M : MSC L Event Var Val)
    (send recv : Event) : Prop where
  send_causal : M.causal send recv
  causal_to_recv_cases :
    ∀ {g}, M.causal g recv →
      g = recv ∨
      (∃ p, M.prevLocal recv = some p ∧ M.causal g p) ∨
      M.causal g send

namespace ReceiveCausalContext

variable (M : MSC L Event Var Val)
variable {send recv : Event}

/-- The h-target instantiation for a receive merge on lifelines other
than the receiver's own lifeline.  The receiver lifeline is updated by
the subsequent local event/writeback step, so it is deliberately not part
of this lemma. -/
theorem hTarget_remote
    (hCtx : ReceiveCausalContext M send recv)
    {B : L} (hRemote : B ≠ M.lifeline recv) :
    M.latestVisible recv B =
      chooseLatest M (latestBeforeLocal M recv B)
        (M.latestVisible send B) := by
  cases hPrev : M.prevLocal recv with
  | none =>
      cases hSend : M.latestVisible send B with
      | none =>
          simp [chooseLatest, latestBeforeLocal, hPrev]
          apply M.latestVisible_eq_none
          intro g hLife hCausal
          rcases hCtx.causal_to_recv_cases hCausal with hEq | hRest
          · subst hEq
            exact hRemote hLife.symm
          · rcases hRest with hPrevCase | hSendCase
            · rcases hPrevCase with ⟨p, hPrevSome, _⟩
              rw [hPrev] at hPrevSome
              contradiction
            · exact (M.latestVisible_none hSend) g hLife hSendCase
      | some sLatest =>
          simp [chooseLatest, latestBeforeLocal, hPrev]
          rcases M.latestVisible_some hSend with
            ⟨hSendLife, hSendCausal, hSendMax⟩
          apply M.latestVisible_eq_some hSendLife
            (M.causal_trans hSendCausal hCtx.send_causal)
          intro g hLife hCausal
          rcases hCtx.causal_to_recv_cases hCausal with hEq | hRest
          · subst hEq
            exact False.elim (hRemote hLife.symm)
          · rcases hRest with hPrevCase | hSendCase
            · rcases hPrevCase with ⟨p, hPrevSome, _⟩
              rw [hPrev] at hPrevSome
              contradiction
            · exact hSendMax g hLife hSendCase
  | some p =>
      cases hLeft : M.latestVisible p B with
      | none =>
          cases hSend : M.latestVisible send B with
          | none =>
              simp [chooseLatest, latestBeforeLocal, hPrev, hLeft]
              apply M.latestVisible_eq_none
              intro g hLife hCausal
              rcases hCtx.causal_to_recv_cases hCausal with hEq | hRest
              · subst hEq
                exact hRemote hLife.symm
              · rcases hRest with hPrevCase | hSendCase
                · rcases hPrevCase with ⟨q, hPrevQ, hCausalQ⟩
                  have hq : q = p := Option.some.inj (hPrevQ.symm.trans hPrev)
                  subst hq
                  exact (M.latestVisible_none hLeft) g hLife hCausalQ
                · exact (M.latestVisible_none hSend) g hLife hSendCase
          | some sLatest =>
              simp [chooseLatest, latestBeforeLocal, hPrev, hLeft]
              rcases M.latestVisible_some hSend with
                ⟨hSendLife, hSendCausal, hSendMax⟩
              apply M.latestVisible_eq_some hSendLife
                (M.causal_trans hSendCausal hCtx.send_causal)
              intro g hLife hCausal
              rcases hCtx.causal_to_recv_cases hCausal with hEq | hRest
              · subst hEq
                exact False.elim (hRemote hLife.symm)
              · rcases hRest with hPrevCase | hSendCase
                · rcases hPrevCase with ⟨q, hPrevQ, hCausalQ⟩
                  have hq : q = p := Option.some.inj (hPrevQ.symm.trans hPrev)
                  subst hq
                  exact False.elim ((M.latestVisible_none hLeft) g hLife hCausalQ)
                · exact hSendMax g hLife hSendCase
      | some lLatest =>
          cases hSend : M.latestVisible send B with
          | none =>
              simp [chooseLatest, latestBeforeLocal, hPrev, hLeft]
              rcases M.latestVisible_some hLeft with
                ⟨hLeftLife, hLeftCausal, hLeftMax⟩
              rcases M.prevLocal_some hPrev with ⟨hPrevLife, hPrevIdx, _⟩
              have hPrevCausal : M.causal p recv :=
                M.local_causal hPrevLife (Nat.le_of_lt hPrevIdx)
              apply M.latestVisible_eq_some hLeftLife
                (M.causal_trans hLeftCausal hPrevCausal)
              intro g hLife hCausal
              rcases hCtx.causal_to_recv_cases hCausal with hEq | hRest
              · subst hEq
                exact False.elim (hRemote hLife.symm)
              · rcases hRest with hPrevCase | hSendCase
                · rcases hPrevCase with ⟨q, hPrevQ, hCausalQ⟩
                  have hq : q = p := Option.some.inj (hPrevQ.symm.trans hPrev)
                  subst hq
                  exact hLeftMax g hLife hCausalQ
                · exact False.elim ((M.latestVisible_none hSend) g hLife hSendCase)
          | some sLatest =>
              rcases M.latestVisible_some hLeft with
                ⟨hLeftLife, hLeftCausal, hLeftMax⟩
              rcases M.latestVisible_some hSend with
                ⟨hSendLife, hSendCausal, hSendMax⟩
              rcases M.prevLocal_some hPrev with ⟨hPrevLife, hPrevIdx, _⟩
              have hPrevCausal : M.causal p recv :=
                M.local_causal hPrevLife (Nat.le_of_lt hPrevIdx)
              by_cases hIdx : M.localIndex lLatest < M.localIndex sLatest
              · simp [chooseLatest, latestBeforeLocal, hPrev, hLeft, hIdx]
                apply M.latestVisible_eq_some hSendLife
                  (M.causal_trans hSendCausal hCtx.send_causal)
                intro g hLife hCausal
                rcases hCtx.causal_to_recv_cases hCausal with hEq | hRest
                · subst hEq
                  exact False.elim (hRemote hLife.symm)
                · rcases hRest with hPrevCase | hSendCase
                  · rcases hPrevCase with ⟨q, hPrevQ, hCausalQ⟩
                    have hq : q = p := Option.some.inj (hPrevQ.symm.trans hPrev)
                    subst hq
                    exact Nat.le_trans (hLeftMax g hLife hCausalQ)
                      (Nat.le_of_lt hIdx)
                  · exact hSendMax g hLife hSendCase
              · have hLe : M.localIndex sLatest ≤ M.localIndex lLatest :=
                  Nat.le_of_not_gt hIdx
                simp [chooseLatest, latestBeforeLocal, hPrev, hLeft, hIdx]
                apply M.latestVisible_eq_some hLeftLife
                  (M.causal_trans hLeftCausal hPrevCausal)
                intro g hLife hCausal
                rcases hCtx.causal_to_recv_cases hCausal with hEq | hRest
                · subst hEq
                  exact False.elim (hRemote hLife.symm)
                · rcases hRest with hPrevCase | hSendCase
                  · rcases hPrevCase with ⟨q, hPrevQ, hCausalQ⟩
                    have hq : q = p := Option.some.inj (hPrevQ.symm.trans hPrev)
                    subst hq
                    exact hLeftMax g hLife hCausalQ
                  · exact Nat.le_trans (hSendMax g hLife hSendCase) hLe

end ReceiveCausalContext

/-- A monitor state's latest-value component is coherent with an abstract
latest-event map. -/
structure SnapshotCoherent (interp : Pred → List Val → Prop)
    (M : MSC L Event Var Val)
    (latest : L → Option Event)
    (st : MonitorState L Var Val Pred) : Prop where
  latest_some_life :
    ∀ {B f}, latest B = some f → M.lifeline f = B
  clock_some :
    ∀ {B f}, latest B = some f → st.clock B = M.localIndex f
  clock_none :
    ∀ {B}, latest B = none → st.clock B = 0
  var_some :
    ∀ {B x f}, latest B = some f →
      st.varView B x = some (M.val f x)
  var_none :
    ∀ {B x}, latest B = none → st.varView B x = none
  view_some :
    ∀ {B φ f}, latest B = some f →
      st.view B φ = some (Sat interp M φ f)
  view_none :
    ∀ {B φ}, latest B = none → st.view B φ = none

namespace MonitorState

/-- Prepare the owner state for local formula evaluation at the current
event after any receive merge has already happened.  This models the
Algorithm 1 steps that save `old`, increment the local clock, update the
local store, and update owner-local variable views. -/
def prepareLocalEval [DecidableEq L]
    (owner : L) (interp : Pred → List Val → Prop)
    (M : MSC L Event Var Val) (e : Event)
    (st : MonitorState L Var Val Pred) :
    MonitorState L Var Val Pred where
  clock B :=
    if B = owner then M.localIndex e else st.clock B
  store x := M.val e x
  old φ :=
    match M.prevLocal e with
    | none => False
    | some p => Sat interp M φ p
  view := st.view
  varView B x :=
    if B = owner then some (M.val e x) else st.varView B x

/-- Write back the owner-local formula values after local evaluation.
This models the Algorithm 1 step that stores the newly evaluated values
as the latest Boolean view of the owner lifeline. -/
def writeLocalViews [DecidableEq L]
    (owner : L) (interp : Pred → List Val → Prop)
    (st : MonitorState L Var Val Pred) :
    MonitorState L Var Val Pred where
  clock := st.clock
  store := st.store
  old := st.old
  view B φ :=
    if B = owner then
      some (MonitorState.Eval owner interp st φ)
    else
      st.view B φ
  varView := st.varView

/-- Merge the latest-value part of two monitor states as in the receive
case of Algorithm 1.  The incoming state is used exactly when it is ahead
on a lifeline.  Local store and old values belong to the receiving
lifeline and are therefore kept from the left state. -/
def mergeViews [DecidableEq L]
    (left right : MonitorState L Var Val Pred) :
    MonitorState L Var Val Pred where
  clock B := max (left.clock B) (right.clock B)
  store := left.store
  old := left.old
  view B φ :=
    if left.clock B < right.clock B then right.view B φ else left.view B φ
  varView B x :=
    if left.clock B < right.clock B then right.varView B x else left.varView B x

end MonitorState

namespace SnapshotCoherent

variable [DecidableEq L]
variable (interp : Pred → List Val → Prop)
variable (M : MSC L Event Var Val)

/-- A coherent post-merge snapshot becomes a coherent pre-evaluation
state for the current event after the owner-local update steps have run.

The hypothesis `hRemoteLatest` supplies the receive h-target fact for
all non-owner lifelines.  The owner lifeline is handled here by the local
clock/store/variable update. -/
theorem prepareLocalEval_coherent
    {latest : L → Option Event}
    {st : MonitorState L Var Val Pred}
    {A : L} {e : Event}
    (hSnap : SnapshotCoherent interp M latest st)
    (hOwner : M.lifeline e = A)
    (hRemoteLatest :
      ∀ {B}, B ≠ A → latest B = M.latestVisible e B) :
    CoherentPreEval interp M A e
      (MonitorState.prepareLocalEval A interp M e st) := by
  constructor
  · exact hOwner
  · intro x
    rfl
  · intro B f hLatest
    by_cases hBA : B = A
    · have hLatestA : M.latestVisible e A = some f := by
        simpa [hBA] using hLatest
      have hSelf : M.latestVisible e A = some e := by
        rw [← hOwner]
        exact M.latestVisible_self e
      have hf : f = e := M.latestVisible_unique hLatestA hSelf
      simp [MonitorState.prepareLocalEval, hBA, hf]
    · have hLatestRemote : latest B = some f := by
        rw [hRemoteLatest hBA, hLatest]
      have hClock := hSnap.clock_some hLatestRemote
      simp [MonitorState.prepareLocalEval, hBA, hClock]
  · intro B hLatest
    by_cases hBA : B = A
    · have hLatestA : M.latestVisible e A = none := by
        simpa [hBA] using hLatest
      have hSelf : M.latestVisible e A = some e := by
        rw [← hOwner]
        exact M.latestVisible_self e
      rw [hSelf] at hLatestA
      contradiction
    · have hLatestRemote : latest B = none := by
        rw [hRemoteLatest hBA, hLatest]
      have hClock := hSnap.clock_none hLatestRemote
      simp [MonitorState.prepareLocalEval, hBA, hClock]
  · intro B x f hLatest
    by_cases hBA : B = A
    · have hLatestA : M.latestVisible e A = some f := by
        simpa [hBA] using hLatest
      have hSelf : M.latestVisible e A = some e := by
        rw [← hOwner]
        exact M.latestVisible_self e
      have hf : f = e := M.latestVisible_unique hLatestA hSelf
      simp [MonitorState.prepareLocalEval, hBA, hf]
    · have hLatestRemote : latest B = some f := by
        rw [hRemoteLatest hBA, hLatest]
      have hVar := hSnap.var_some (x := x) hLatestRemote
      simp [MonitorState.prepareLocalEval, hBA, hVar]
  · intro B x hLatest
    by_cases hBA : B = A
    · have hLatestA : M.latestVisible e A = none := by
        simpa [hBA] using hLatest
      have hSelf : M.latestVisible e A = some e := by
        rw [← hOwner]
        exact M.latestVisible_self e
      rw [hSelf] at hLatestA
      contradiction
    · have hLatestRemote : latest B = none := by
        rw [hRemoteLatest hBA, hLatest]
      have hVar := hSnap.var_none (x := x) hLatestRemote
      simp [MonitorState.prepareLocalEval, hBA, hVar]
  · intro B φ f hBA hLatest
    have hLatestRemote : latest B = some f := by
      rw [hRemoteLatest hBA, hLatest]
    exact hSnap.view_some hLatestRemote
  · intro B φ hBA hLatest
    have hLatestRemote : latest B = none := by
      rw [hRemoteLatest hBA, hLatest]
    exact hSnap.view_none hLatestRemote
  · intro φ f hPrev
    simp [MonitorState.prepareLocalEval, hPrev]
  · intro φ hPrev
    simp [MonitorState.prepareLocalEval, hPrev]

end SnapshotCoherent

namespace CoherentPreEval

variable [DecidableEq L]
variable (interp : Pred → List Val → Prop)
variable (M : MSC L Event Var Val)

/-- After local formula evaluation has written the owner entries back
into `view A`, a coherent pre-evaluation state yields a coherent
latest-value snapshot for the current event. -/
theorem writeLocalViews_snapshot
    {A : L} {e : Event} {st : MonitorState L Var Val Pred}
    (h : CoherentPreEval interp M A e st) :
    SnapshotCoherent interp M (fun B => M.latestVisible e B)
      (MonitorState.writeLocalViews A interp st) := by
  constructor
  · intro B f hLatest
    exact (M.latestVisible_some hLatest).1
  · intro B f hLatest
    exact h.clock_some hLatest
  · intro B hLatest
    exact h.clock_none hLatest
  · intro B x f hLatest
    exact h.var_some hLatest
  · intro B x hLatest
    exact h.var_none hLatest
  · intro B φ latestEv hLatest
    by_cases hBA : B = A
    · have hLatestA : M.latestVisible e A = some latestEv := by
        simpa [hBA] using hLatest
      have hSelf : M.latestVisible e A = some e := by
        rw [← h.owner_eq]
        exact M.latestVisible_self e
      have hf : latestEv = e := M.latestVisible_unique hLatestA hSelf
      have hEval :
          MonitorState.Eval A interp st φ ↔ Sat interp M φ e :=
        local_eval_correct
          (interp := interp) (M := M) (A := A) (e := e) (st := st) h φ
      have hProp :
          MonitorState.Eval A interp st φ = Sat interp M φ latestEv := by
        rw [hf]
        exact propext hEval
      simp [MonitorState.writeLocalViews, hBA, hProp]
    · have hView : st.view B φ = some (Sat interp M φ latestEv) :=
        h.view_some hBA hLatest
      simp [MonitorState.writeLocalViews, hBA, hView]
  · intro B φ hLatest
    by_cases hBA : B = A
    · have hLatestA : M.latestVisible e A = none := by
        simpa [hBA] using hLatest
      have hSelf : M.latestVisible e A = some e := by
        rw [← h.owner_eq]
        exact M.latestVisible_self e
      rw [hSelf] at hLatestA
      contradiction
    · have hView : st.view B φ = none :=
        h.view_none hBA hLatest
      simp [MonitorState.writeLocalViews, hBA, hView]

end CoherentPreEval

namespace SnapshotCoherent

variable [DecidableEq L]
variable (interp : Pred → List Val → Prop)
variable (M : MSC L Event Var Val)
variable (leftLatest rightLatest targetLatest : L → Option Event)
variable (left right : MonitorState L Var Val Pred)

/-- Componentwise merge preserves latest-value coherence, provided the
target latest-event map is obtained by selecting the event with the larger
local index on each lifeline. -/
theorem merge_correct
    (hLeft : SnapshotCoherent interp M leftLatest left)
    (hRight : SnapshotCoherent interp M rightLatest right)
    (hTarget :
      ∀ B, targetLatest B =
        chooseLatest M (leftLatest B) (rightLatest B)) :
    SnapshotCoherent interp M targetLatest
      (MonitorState.mergeViews left right) := by
  constructor
  · intro B f hLatest
    rw [hTarget B] at hLatest
    cases hL : leftLatest B with
    | none =>
        cases hR : rightLatest B with
        | none =>
            simp [chooseLatest, hL, hR] at hLatest
        | some r =>
            simp [chooseLatest, hL, hR] at hLatest
            subst hLatest
            exact hRight.latest_some_life hR
    | some l =>
        cases hR : rightLatest B with
        | none =>
            simp [chooseLatest, hL, hR] at hLatest
            subst hLatest
            exact hLeft.latest_some_life hL
        | some r =>
            by_cases hIdx : M.localIndex l < M.localIndex r
            · simp [chooseLatest, hL, hR, hIdx] at hLatest
              subst hLatest
              exact hRight.latest_some_life hR
            · simp [chooseLatest, hL, hR, hIdx] at hLatest
              subst hLatest
              exact hLeft.latest_some_life hL
  · intro B f hLatest
    rw [hTarget B] at hLatest
    cases hL : leftLatest B with
    | none =>
        cases hR : rightLatest B with
        | none =>
            simp [chooseLatest, hL, hR] at hLatest
        | some r =>
            have hLC : left.clock B = 0 := hLeft.clock_none hL
            have hRC : right.clock B = M.localIndex r := hRight.clock_some hR
            simp [MonitorState.mergeViews, chooseLatest, hL, hR] at hLatest ⊢
            subst hLatest
            rw [hLC, hRC]
            exact Nat.max_eq_right (Nat.le_of_lt (M.localIndex_pos r))
    | some l =>
        cases hR : rightLatest B with
        | none =>
            have hLC : left.clock B = M.localIndex l := hLeft.clock_some hL
            have hRC : right.clock B = 0 := hRight.clock_none hR
            simp [MonitorState.mergeViews, chooseLatest, hL, hR] at hLatest ⊢
            subst hLatest
            rw [hLC, hRC]
            exact Nat.max_eq_left (Nat.zero_le _)
        | some r =>
            have hLC : left.clock B = M.localIndex l := hLeft.clock_some hL
            have hRC : right.clock B = M.localIndex r := hRight.clock_some hR
            by_cases hIdx : M.localIndex l < M.localIndex r
            · simp [MonitorState.mergeViews, chooseLatest, hL, hR, hIdx] at hLatest ⊢
              subst hLatest
              rw [hLC, hRC]
              exact Nat.max_eq_right (Nat.le_of_lt hIdx)
            · have hLe : M.localIndex r ≤ M.localIndex l := Nat.le_of_not_gt hIdx
              simp [MonitorState.mergeViews, chooseLatest, hL, hR, hIdx] at hLatest ⊢
              subst hLatest
              rw [hLC, hRC]
              exact Nat.max_eq_left hLe
  · intro B hLatest
    rw [hTarget B] at hLatest
    cases hL : leftLatest B with
    | none =>
        cases hR : rightLatest B with
        | none =>
            have hLC : left.clock B = 0 := hLeft.clock_none hL
            have hRC : right.clock B = 0 := hRight.clock_none hR
            simp [MonitorState.mergeViews, hLC, hRC]
        | some r =>
            simp [chooseLatest, hL, hR] at hLatest
    | some l =>
        cases hR : rightLatest B with
        | none =>
            simp [chooseLatest, hL, hR] at hLatest
        | some r =>
            by_cases hIdx : M.localIndex l < M.localIndex r
            · simp [chooseLatest, hL, hR, hIdx] at hLatest
            · simp [chooseLatest, hL, hR, hIdx] at hLatest
  · intro B x f hLatest
    rw [hTarget B] at hLatest
    cases hL : leftLatest B with
    | none =>
        cases hR : rightLatest B with
        | none =>
            simp [chooseLatest, hL, hR] at hLatest
        | some r =>
            have hLC : left.clock B = 0 := hLeft.clock_none hL
            have hRC : right.clock B = M.localIndex r := hRight.clock_some hR
            have hVar : right.varView B x = some (M.val r x) :=
              hRight.var_some hR
            simp [MonitorState.mergeViews, chooseLatest, hL, hR] at hLatest ⊢
            subst hLatest
            rw [hLC, hRC, if_pos (M.localIndex_pos r), hVar]
    | some l =>
        cases hR : rightLatest B with
        | none =>
            have hLC : left.clock B = M.localIndex l := hLeft.clock_some hL
            have hRC : right.clock B = 0 := hRight.clock_none hR
            have hVar : left.varView B x = some (M.val l x) :=
              hLeft.var_some hL
            simp [MonitorState.mergeViews, chooseLatest, hL, hR] at hLatest ⊢
            subst hLatest
            rw [hLC, hRC, if_neg (Nat.not_lt_zero _), hVar]
        | some r =>
            have hLC : left.clock B = M.localIndex l := hLeft.clock_some hL
            have hRC : right.clock B = M.localIndex r := hRight.clock_some hR
            by_cases hIdx : M.localIndex l < M.localIndex r
            · have hVar : right.varView B x = some (M.val r x) :=
                hRight.var_some hR
              simp [MonitorState.mergeViews, chooseLatest, hL, hR, hIdx] at hLatest ⊢
              subst hLatest
              rw [hLC, hRC, if_pos hIdx, hVar]
            · have hVar : left.varView B x = some (M.val l x) :=
                hLeft.var_some hL
              simp [MonitorState.mergeViews, chooseLatest, hL, hR, hIdx] at hLatest ⊢
              subst hLatest
              rw [hLC, hRC, if_neg hIdx, hVar]
  · intro B x hLatest
    rw [hTarget B] at hLatest
    cases hL : leftLatest B with
    | none =>
        cases hR : rightLatest B with
        | none =>
            have hLC : left.clock B = 0 := hLeft.clock_none hL
            have hRC : right.clock B = 0 := hRight.clock_none hR
            have hVar : left.varView B x = none := hLeft.var_none hL
            simp [MonitorState.mergeViews, chooseLatest, hL, hR] at hLatest ⊢
            rw [hLC, hRC, if_neg (Nat.lt_irrefl 0), hVar]
        | some r =>
            simp [chooseLatest, hL, hR] at hLatest
    | some l =>
        cases hR : rightLatest B with
        | none =>
            simp [chooseLatest, hL, hR] at hLatest
        | some r =>
            by_cases hIdx : M.localIndex l < M.localIndex r
            · simp [chooseLatest, hL, hR, hIdx] at hLatest
            · simp [chooseLatest, hL, hR, hIdx] at hLatest
  · intro B φ f hLatest
    rw [hTarget B] at hLatest
    cases hL : leftLatest B with
    | none =>
        cases hR : rightLatest B with
        | none =>
            simp [chooseLatest, hL, hR] at hLatest
        | some r =>
            have hLC : left.clock B = 0 := hLeft.clock_none hL
            have hRC : right.clock B = M.localIndex r := hRight.clock_some hR
            have hView : right.view B φ = some (Sat interp M φ r) :=
              hRight.view_some hR
            simp [MonitorState.mergeViews, chooseLatest, hL, hR] at hLatest ⊢
            subst hLatest
            rw [hLC, hRC, if_pos (M.localIndex_pos r), hView]
    | some l =>
        cases hR : rightLatest B with
        | none =>
            have hLC : left.clock B = M.localIndex l := hLeft.clock_some hL
            have hRC : right.clock B = 0 := hRight.clock_none hR
            have hView : left.view B φ = some (Sat interp M φ l) :=
              hLeft.view_some hL
            simp [MonitorState.mergeViews, chooseLatest, hL, hR] at hLatest ⊢
            subst hLatest
            rw [hLC, hRC, if_neg (Nat.not_lt_zero _), hView]
        | some r =>
            have hLC : left.clock B = M.localIndex l := hLeft.clock_some hL
            have hRC : right.clock B = M.localIndex r := hRight.clock_some hR
            by_cases hIdx : M.localIndex l < M.localIndex r
            · have hView : right.view B φ = some (Sat interp M φ r) :=
                hRight.view_some hR
              simp [MonitorState.mergeViews, chooseLatest, hL, hR, hIdx] at hLatest ⊢
              subst hLatest
              rw [hLC, hRC, if_pos hIdx, hView]
            · have hView : left.view B φ = some (Sat interp M φ l) :=
                hLeft.view_some hL
              simp [MonitorState.mergeViews, chooseLatest, hL, hR, hIdx] at hLatest ⊢
              subst hLatest
              rw [hLC, hRC, if_neg hIdx, hView]
  · intro B φ hLatest
    rw [hTarget B] at hLatest
    cases hL : leftLatest B with
    | none =>
        cases hR : rightLatest B with
        | none =>
            have hLC : left.clock B = 0 := hLeft.clock_none hL
            have hRC : right.clock B = 0 := hRight.clock_none hR
            have hView : left.view B φ = none := hLeft.view_none hL
            simp [MonitorState.mergeViews, chooseLatest, hL, hR] at hLatest ⊢
            rw [hLC, hRC, if_neg (Nat.lt_irrefl 0), hView]
        | some r =>
            simp [chooseLatest, hL, hR] at hLatest
    | some l =>
        cases hR : rightLatest B with
        | none =>
            simp [chooseLatest, hL, hR] at hLatest
        | some r =>
            by_cases hIdx : M.localIndex l < M.localIndex r
            · simp [chooseLatest, hL, hR, hIdx] at hLatest
            · simp [chooseLatest, hL, hR, hIdx] at hLatest

/-- Paper-facing name for the receive-merge selection theorem. -/
theorem receive_merge_correct
    (hLeft : SnapshotCoherent interp M leftLatest left)
    (hRight : SnapshotCoherent interp M rightLatest right)
    (hTarget :
      ∀ B, targetLatest B =
        chooseLatest M (leftLatest B) (rightLatest B)) :
    SnapshotCoherent interp M targetLatest
      (MonitorState.mergeViews left right) :=
  merge_correct
    (interp := interp) (M := M)
    (leftLatest := leftLatest) (rightLatest := rightLatest)
    (targetLatest := targetLatest) (left := left) (right := right)
    hLeft hRight hTarget

/-- Receive-event instance of the monitor-state invariant.

Starting from a receiver snapshot before the receive and the snapshot
carried by the matching send, the Algorithm 1 receive path

`mergeViews → prepareLocalEval → writeLocalViews`

produces a snapshot coherent with the latest-visible map at the receive
event. -/
theorem monitor_invariants_receive
    {send recv : Event}
    {receiverBefore incoming : MonitorState L Var Val Pred}
    (hCtx : ReceiveCausalContext M send recv)
    (hReceiver :
      SnapshotCoherent interp M (latestBeforeLocal M recv) receiverBefore)
    (hIncoming :
      SnapshotCoherent interp M (fun B => M.latestVisible send B) incoming) :
    SnapshotCoherent interp M (fun B => M.latestVisible recv B)
      (MonitorState.writeLocalViews (M.lifeline recv) interp
        (MonitorState.prepareLocalEval (M.lifeline recv) interp M recv
          (MonitorState.mergeViews receiverBefore incoming))) := by
  let mergedLatest : L → Option Event :=
    fun B => chooseLatest M (latestBeforeLocal M recv B)
      (M.latestVisible send B)
  let merged : MonitorState L Var Val Pred :=
    MonitorState.mergeViews receiverBefore incoming
  have hMerged : SnapshotCoherent interp M mergedLatest merged :=
    receive_merge_correct
      (interp := interp) (M := M)
      (leftLatest := latestBeforeLocal M recv)
      (rightLatest := fun B => M.latestVisible send B)
      (targetLatest := mergedLatest)
      (left := receiverBefore) (right := incoming)
      hReceiver hIncoming (by intro B; rfl)
  have hPre :
      CoherentPreEval interp M (M.lifeline recv) recv
        (MonitorState.prepareLocalEval (M.lifeline recv) interp M recv merged) :=
    prepareLocalEval_coherent
      (interp := interp) (M := M)
      (latest := mergedLatest) (st := merged)
      hMerged rfl
      (by
        intro B hRemote
        exact (ReceiveCausalContext.hTarget_remote
          (M := M) hCtx hRemote).symm)
  exact CoherentPreEval.writeLocalViews_snapshot
    (interp := interp) (M := M) hPre

/-- Local-event instance of the monitor-state invariant.

For events whose local pre-evaluation state is already coherent, the
Algorithm 1 writeback step gives the post-event latest-value snapshot.
This is the non-receive/local counterpart of the receive theorem above;
any event-kind-specific proof only has to establish the `CoherentPreEval`
premise. -/
theorem monitor_invariants_local
    {e : Event} {st : MonitorState L Var Val Pred}
    (hPre : CoherentPreEval interp M (M.lifeline e) e st) :
    SnapshotCoherent interp M (fun B => M.latestVisible e B)
      (MonitorState.writeLocalViews (M.lifeline e) interp st) :=
  CoherentPreEval.writeLocalViews_snapshot
    (interp := interp) (M := M) hPre

/-- The two event-update paths formalized at this proof layer. -/
inductive EventUpdateResult :
    Event → MonitorState L Var Val Pred → Prop where
  | localStep {e : Event} {st : MonitorState L Var Val Pred}
      (hPre : CoherentPreEval interp M (M.lifeline e) e st) :
      EventUpdateResult e
        (MonitorState.writeLocalViews (M.lifeline e) interp st)
  | receiveStep {send recv : Event}
      {receiverBefore incoming : MonitorState L Var Val Pred}
      (hCtx : ReceiveCausalContext M send recv)
      (hReceiver :
        SnapshotCoherent interp M (latestBeforeLocal M recv) receiverBefore)
      (hIncoming :
        SnapshotCoherent interp M (fun B => M.latestVisible send B) incoming) :
      EventUpdateResult recv
        (MonitorState.writeLocalViews (M.lifeline recv) interp
          (MonitorState.prepareLocalEval (M.lifeline recv) interp M recv
            (MonitorState.mergeViews receiverBefore incoming)))

/-- Full event-update invariant for the formalized event-update paths. -/
theorem monitor_invariants
    {e : Event} {post : MonitorState L Var Val Pred}
    (hUpdate : EventUpdateResult (interp := interp) (M := M) e post) :
    SnapshotCoherent interp M (fun B => M.latestVisible e B) post := by
  cases hUpdate with
  | localStep hPre =>
      exact monitor_invariants_local
        (interp := interp) (M := M) hPre
  | receiveStep hCtx hReceiver hIncoming =>
      exact monitor_invariants_receive
        (interp := interp) (M := M) hCtx hReceiver hIncoming

/-- Formula value read from the owner-local latest-value view after an
event update. -/
def ownerFormulaValue
    (e : Event) (st : MonitorState L Var Val Pred)
    (φ : Formula L Var Pred) : Prop :=
  match st.view (M.lifeline e) φ with
  | none => False
  | some p => p

omit [DecidableEq L] in
/-- Monitor correctness from the post-event invariant. -/
theorem monitor_correct
    {e : Event} {post : MonitorState L Var Val Pred}
    (hInv : SnapshotCoherent interp M (fun B => M.latestVisible e B) post)
    (φ : Formula L Var Pred) :
    ownerFormulaValue (M := M) e post φ ↔ Sat interp M φ e := by
  have hView :
      post.view (M.lifeline e) φ = some (Sat interp M φ e) :=
    hInv.view_some (B := M.lifeline e) (φ := φ) (f := e)
      (M.latestVisible_self e)
  simp [ownerFormulaValue, hView]

/-- End-to-end monitor correctness for the formalized event-update paths. -/
theorem monitor_correct_after_update
    {e : Event} {post : MonitorState L Var Val Pred}
    (hUpdate : EventUpdateResult (interp := interp) (M := M) e post)
    (φ : Formula L Var Pred) :
    ownerFormulaValue (M := M) e post φ ↔ Sat interp M φ e :=
  monitor_correct
    (interp := interp) (M := M)
    (monitor_invariants (interp := interp) (M := M) hUpdate) φ

end SnapshotCoherent

end CPLMonitor
